export const SITE_CONFIG = {
    name: "SmileCare Dental Clinic",
    description: "Professional dental care for the whole family regarding Ahmedabad. Experience gentle, comprehensive dental services in a comfortable environment.",
    url: "https://smilecare-ahmedabad.com",
    ogImage: "/images/og-image.jpg",
    phone: "+91 98765 43210",
    email: "info@smilecare-ahmedabad.com",
    address: {
        street: "301, Titanium City Center, Satellite",
        city: "Ahmedabad",
        state: "Gujarat",
        zip: "380015",
        country: "India",
    },
    hours: {
        weekdays: "9:00 AM - 8:00 PM",
        saturday: "9:00 AM - 6:00 PM",
        sunday: "10:00 AM - 2:00 PM",
    },
    social: {
        facebook: "https://facebook.com/smilecare",
        instagram: "https://instagram.com/smilecare",
        twitter: "https://twitter.com/smilecare",
        linkedin: "https://linkedin.com/company/smilecare",
    },
};

export const NAV_LINKS = [
    { href: "/", label: "Home" },
    { href: "/about", label: "About" },
    { href: "/services", label: "Services" },
    { href: "/team", label: "Our Team" },
    { href: "/blog", label: "Blog" },
    { href: "/contact", label: "Contact" },
];

export const APPOINTMENT_STATUS = {
    PENDING: "pending",
    CONFIRMED: "confirmed",
    COMPLETED: "completed",
    CANCELLED: "cancelled",
} as const;

export const SERVICES_DATA = [
    {
        id: "1",
        title: "General Dentistry",
        description: "Comprehensive dental care including check-ups, cleanings, and preventive treatments to maintain your oral health.",
        duration: 60,
        price: 500,
        image: "/images/services/general-dentistry.jpg",
        icon: "Stethoscope",
    },
    {
        id: "2",
        title: "Teeth Whitening",
        description: "Professional whitening treatments to brighten your smile and remove stains for a radiant, confident appearance.",
        duration: 90,
        price: 5000,
        image: "/images/services/teeth-whitening.jpg",
        icon: "Sparkles",
    },
    {
        id: "3",
        title: "Dental Implants",
        description: "Permanent tooth replacement solution that looks, feels, and functions like natural teeth.",
        duration: 120,
        price: 25000,
        image: "/images/services/dental-implants.jpg",
        icon: "Component",
    },
    {
        id: "4",
        title: "Orthodontics",
        description: "Straighten your teeth with modern braces or clear aligners for a perfectly aligned smile.",
        duration: 45,
        price: 40000,
        image: "/images/services/orthodontics.jpg",
        icon: "AlignCenter",
    },
    {
        id: "5",
        title: "Root Canal Treatment",
        description: "Save your natural tooth with our gentle, effective root canal therapy performed with precision.",
        duration: 90,
        price: 4000,
        image: "/images/services/root-canal.jpg",
        icon: "Heart",
    },
    {
        id: "6",
        title: "Cosmetic Dentistry",
        description: "Transform your smile with veneers, bonding, and other cosmetic procedures for a stunning look.",
        duration: 60,
        price: 8000,
        image: "/images/services/cosmetic-dentistry.jpg",
        icon: "Gem",
    },
    {
        id: "7",
        title: "Pediatric Dentistry",
        description: "Gentle, child-friendly dental care designed to make visits fun and stress-free for young patients.",
        duration: 45,
        price: 800,
        image: "/images/services/pediatric-dentistry.jpg",
        icon: "Baby",
    },
    {
        id: "8",
        title: "Emergency Dental Care",
        description: "Immediate attention for dental emergencies including severe pain, broken teeth, and infections.",
        duration: 60,
        price: 1000,
        image: "/images/services/emergency-care.jpg",
        icon: "AlertCircle",
    },
];

export const DOCTORS_DATA = [
    {
        id: "1",
        name: "Dr. Priya Patel",
        title: "Lead Dentist & Founder",
        bio: "With over 15 years of experience, Dr. Patel specializes in cosmetic and restorative dentistry. She founded SmileCare to provide world-class dental care in Ahmedabad.",
        image: "/images/team/sarah-mitchell.jpg",
        specializations: ["Cosmetic Dentistry", "Dental Implants", "General Dentistry"],
        education: "MDS, Gujarat University",
    },
    {
        id: "2",
        name: "Dr. Rajesh Kumar",
        title: "Orthodontist",
        bio: "Dr. Kumar is a certified orthodontist with expertise in Invisalign and traditional braces. He is passionate about creating beautiful, healthy smiles for patients of all ages.",
        image: "/images/team/james-chen.jpg",
        specializations: ["Orthodontics", "Invisalign", "Pediatric Orthodontics"],
        education: "MDS, All India Institute of Medical Sciences",
    },
    {
        id: "3",
        name: "Dr. Anjali Mehta",
        title: "Pediatric Dentist",
        bio: "Dr. Mehta loves working with children and has a special talent for making dental visits enjoyable. She focuses on preventive care and early intervention.",
        image: "/images/team/emily-rodriguez.jpg",
        specializations: ["Pediatric Dentistry", "Preventive Care", "Sedation Dentistry"],
        education: "MDS, Manipal College of Dental Sciences",
    },
    {
        id: "4",
        name: "Dr. Vikram Shah",
        title: "Oral Surgeon",
        bio: "Dr. Shah brings 20 years of surgical expertise to our team. He specializes in dental implants, wisdom teeth extraction, and complex oral surgeries.",
        image: "/images/team/michael-thompson.jpg",
        specializations: ["Oral Surgery", "Dental Implants", "Wisdom Teeth"],
        education: "MDS, Oral & Maxillofacial Surgery",
    },
];

export const TESTIMONIALS = [
    {
        id: "1",
        name: "Amit Shah",
        text: "SmileCare transformed my smile. Dr. Patel is incredibly professional and the facility is state-of-the-art. Highly recommended!",
        rating: 5,
        treatment: "Teeth Whitening",
    },
    {
        id: "2",
        name: "Sneha Reddy",
        text: "I was terrified of dentists until I came here. Dr. Kumar made me feel completely at ease. Best dental clinic in Ahmedabad.",
        rating: 5,
        treatment: "Orthodontics",
    },
    {
        id: "3",
        name: "Rahul Sharma",
        text: "My kids love coming to see Dr. Mehta. She is wonderful with children. The clinic is very clean and hygienic.",
        rating: 5,
        treatment: "Pediatric Dentistry",
    },
    {
        id: "4",
        name: "Kavita Iyer",
        text: "Got my dental implants done by Dr. Shah. The procedure was smooth and the results are fantastic. Great value for money.",
        rating: 5,
        treatment: "Dental Implants",
    },
];

export const BLOG_POSTS = [
    {
        id: "1",
        title: "10 Tips for Maintaining Healthy Teeth in Indian Diet",
        slug: "tips-for-healthy-teeth-indian-diet",
        excerpt: "Discover how to enjoy Indian cuisine while keeping your teeth and gums healthy with these expert tips.",
        content: "",
        featuredImage: "/images/blog/healthy-teeth.jpg",
        tags: ["Oral Health", "Diet", "Tips"],
        publishedAt: "2024-01-15",
        author: "Dr. Priya Patel",
    },
    {
        id: "2",
        title: "Dental Implants: A Permanent Solution",
        slug: "understanding-dental-implants",
        excerpt: "Learn everything you need to know about dental implants, the procedure, and why they are a great investment.",
        content: "",
        featuredImage: "/images/blog/dental-implants.jpg",
        tags: ["Dental Implants", "Procedures", "Guide"],
        publishedAt: "2024-01-10",
        author: "Dr. Vikram Shah",
    },
    {
        id: "3",
        title: "Invisalign vs Braces: What's Best for You?",
        slug: "invisalign-pros-and-cons",
        excerpt: "Comparing clear aligners and traditional braces to help you make the right choice for your smile.",
        content: "",
        featuredImage: "/images/blog/invisalign.jpg",
        tags: ["Orthodontics", "Invisalign", "Treatment Options"],
        publishedAt: "2024-01-05",
        author: "Dr. Rajesh Kumar",
    },
];
