export const SITE_CONFIG = {
    name: "SmileCare Dental Clinic",
    description: "Professional dental care for the whole family. Experience gentle, comprehensive dental services in a comfortable environment.",
    url: "https://smilecare-dental.com",
    ogImage: "/images/og-image.jpg",
    phone: "+1 (555) 123-4567",
    email: "info@smilecare-dental.com",
    address: {
        street: "123 Dental Avenue",
        city: "Los Angeles",
        state: "CA",
        zip: "90001",
        country: "United States",
    },
    hours: {
        weekdays: "8:00 AM - 6:00 PM",
        saturday: "9:00 AM - 3:00 PM",
        sunday: "Closed",
    },
    social: {
        facebook: "https://facebook.com/smilecare",
        instagram: "https://instagram.com/smilecare",
        twitter: "https://twitter.com/smilecare",
        linkedin: "https://linkedin.com/company/smilecare",
    },
};

export const NAV_LINKS = [
    { href: "/", label: "Home" },
    { href: "/about", label: "About" },
    { href: "/services", label: "Services" },
    { href: "/team", label: "Our Team" },
    { href: "/blog", label: "Blog" },
    { href: "/contact", label: "Contact" },
];

export const APPOINTMENT_STATUS = {
    PENDING: "pending",
    CONFIRMED: "confirmed",
    COMPLETED: "completed",
    CANCELLED: "cancelled",
} as const;

export const SERVICES_DATA = [
    {
        id: "1",
        title: "General Dentistry",
        description: "Comprehensive dental care including check-ups, cleanings, and preventive treatments to maintain your oral health.",
        duration: 60,
        price: 150,
        image: "/images/services/general-dentistry.jpg",
        icon: "Stethoscope",
    },
    {
        id: "2",
        title: "Teeth Whitening",
        description: "Professional whitening treatments to brighten your smile and remove stains for a radiant, confident appearance.",
        duration: 90,
        price: 350,
        image: "/images/services/teeth-whitening.jpg",
        icon: "Sparkles",
    },
    {
        id: "3",
        title: "Dental Implants",
        description: "Permanent tooth replacement solution that looks, feels, and functions like natural teeth.",
        duration: 120,
        price: 2500,
        image: "/images/services/dental-implants.jpg",
        icon: "Component",
    },
    {
        id: "4",
        title: "Orthodontics",
        description: "Straighten your teeth with modern braces or clear aligners for a perfectly aligned smile.",
        duration: 45,
        price: 5000,
        image: "/images/services/orthodontics.jpg",
        icon: "AlignCenter",
    },
    {
        id: "5",
        title: "Root Canal Treatment",
        description: "Save your natural tooth with our gentle, effective root canal therapy performed with precision.",
        duration: 90,
        price: 800,
        image: "/images/services/root-canal.jpg",
        icon: "Heart",
    },
    {
        id: "6",
        title: "Cosmetic Dentistry",
        description: "Transform your smile with veneers, bonding, and other cosmetic procedures for a stunning look.",
        duration: 60,
        price: 1200,
        image: "/images/services/cosmetic-dentistry.jpg",
        icon: "Gem",
    },
    {
        id: "7",
        title: "Pediatric Dentistry",
        description: "Gentle, child-friendly dental care designed to make visits fun and stress-free for young patients.",
        duration: 45,
        price: 120,
        image: "/images/services/pediatric-dentistry.jpg",
        icon: "Baby",
    },
    {
        id: "8",
        title: "Emergency Dental Care",
        description: "Immediate attention for dental emergencies including severe pain, broken teeth, and infections.",
        duration: 60,
        price: 200,
        image: "/images/services/emergency-care.jpg",
        icon: "AlertCircle",
    },
];

export const DOCTORS_DATA = [
    {
        id: "1",
        name: "Dr. Sarah Mitchell",
        title: "Lead Dentist & Founder",
        bio: "With over 15 years of experience, Dr. Mitchell specializes in cosmetic and restorative dentistry. She founded SmileCare with a vision to provide exceptional dental care in a warm, welcoming environment.",
        image: "/images/team/sarah-mitchell.jpg",
        specializations: ["Cosmetic Dentistry", "Dental Implants", "General Dentistry"],
        education: "DDS, UCLA School of Dentistry",
    },
    {
        id: "2",
        name: "Dr. James Chen",
        title: "Orthodontist",
        bio: "Dr. Chen is a board-certified orthodontist with expertise in Invisalign and traditional braces. He is passionate about creating beautiful, healthy smiles for patients of all ages.",
        image: "/images/team/james-chen.jpg",
        specializations: ["Orthodontics", "Invisalign", "Pediatric Orthodontics"],
        education: "DMD, Harvard School of Dental Medicine",
    },
    {
        id: "3",
        name: "Dr. Emily Rodriguez",
        title: "Pediatric Dentist",
        bio: "Dr. Rodriguez loves working with children and has a special talent for making dental visits enjoyable. She focuses on preventive care and early intervention.",
        image: "/images/team/emily-rodriguez.jpg",
        specializations: ["Pediatric Dentistry", "Preventive Care", "Sedation Dentistry"],
        education: "DDS, NYU College of Dentistry",
    },
    {
        id: "4",
        name: "Dr. Michael Thompson",
        title: "Oral Surgeon",
        bio: "Dr. Thompson brings 20 years of surgical expertise to our team. He specializes in dental implants, wisdom teeth extraction, and complex oral surgeries.",
        image: "/images/team/michael-thompson.jpg",
        specializations: ["Oral Surgery", "Dental Implants", "Wisdom Teeth"],
        education: "DMD, MD, University of Pennsylvania",
    },
];

export const TESTIMONIALS = [
    {
        id: "1",
        name: "Jennifer Adams",
        text: "SmileCare transformed my smile with their amazing whitening treatment. The staff is incredibly friendly and professional. I couldn't be happier with the results!",
        rating: 5,
        treatment: "Teeth Whitening",
    },
    {
        id: "2",
        name: "Robert Martinez",
        text: "I was terrified of dentists until I came here. Dr. Mitchell and her team made me feel completely at ease. Now I actually look forward to my appointments!",
        rating: 5,
        treatment: "General Dentistry",
    },
    {
        id: "3",
        name: "Sarah Kim",
        text: "My kids love coming to see Dr. Rodriguez. She has such a wonderful way with children. The office is modern and welcoming. Highly recommend for families!",
        rating: 5,
        treatment: "Pediatric Dentistry",
    },
    {
        id: "4",
        name: "David Wilson",
        text: "Got my dental implants done here and the results are incredible. The procedure was smooth and the follow-up care was exceptional. Best investment I've made.",
        rating: 5,
        treatment: "Dental Implants",
    },
];

export const BLOG_POSTS = [
    {
        id: "1",
        title: "10 Tips for Maintaining Healthy Teeth Between Visits",
        slug: "tips-for-healthy-teeth",
        excerpt: "Discover the best practices for keeping your teeth and gums healthy at home with these expert-approved tips.",
        content: "",
        featuredImage: "/images/blog/healthy-teeth.jpg",
        tags: ["Oral Health", "Prevention", "Tips"],
        publishedAt: "2024-01-15",
        author: "Dr. Sarah Mitchell",
    },
    {
        id: "2",
        title: "Understanding Dental Implants: A Complete Guide",
        slug: "understanding-dental-implants",
        excerpt: "Learn everything you need to know about dental implants, from the procedure to recovery and long-term care.",
        content: "",
        featuredImage: "/images/blog/dental-implants.jpg",
        tags: ["Dental Implants", "Procedures", "Guide"],
        publishedAt: "2024-01-10",
        author: "Dr. Michael Thompson",
    },
    {
        id: "3",
        title: "Is Invisalign Right for You? Pros and Cons Explained",
        slug: "invisalign-pros-and-cons",
        excerpt: "Considering clear aligners? We break down the advantages and limitations of Invisalign treatment.",
        content: "",
        featuredImage: "/images/blog/invisalign.jpg",
        tags: ["Orthodontics", "Invisalign", "Treatment Options"],
        publishedAt: "2024-01-05",
        author: "Dr. James Chen",
    },
];
